describe('My First Test', () => {
    it('Realizar contato com a empresa para comprar um veiculo', () => {
      cy.visit('https://testes.autoforce.com.br/dealer-bmw-desafio/')
      cy.get(':nth-child(3) > a > .list-vehicles-land__item > .btn').type('Competition M Track')
      cy.get('.conversion-form [name=cpf]').type('04892694193')
      cy.get('.conversion-form [name=name]').type('Sidney Barbosa')
      cy.get('.conversion-form [name=email]').type('sidneybarbosa1999@gmail.com')
      cy.get('.conversion-form [name=phone]').type('61981184989')
      cy.get('.conversion-form [name=cpf]').type('04892694193')
      cy.get('.form-conversion__body [data-type*=select-one][role=listbox][dir=ltr]').click().contains('São Paulo').click()
      cy.get('input[name=phoning]').check({ force: true })
      cy.get('.form-conversion__body [class*=button--primary]').click()
      cy.get('.form-message-overlay').should('contain.text','Solicitação realizada com sucesso!')
   })
    it('Sistema mostrar mensagem de campo obrigatório no formulário', () => {
      cy.visit('https://testes.autoforce.com.br/dealer-bmw-desafio/')
      cy.get(':nth-child(3) > a > .list-vehicles-land__item > .btn').type('Competition M Track')
      cy.get('.form-conversion__body [class*=button--primary]').click()
      cy.get('#bouncer-error_cpf').should('have.text','Por favor, preencha esse campo')
      cy.get('#bouncer-error_name').should('have.text','Por favor, preencha esse campo')
      cy.get('#bouncer-error_phone').should('have.text','Por favor, preencha esse campo')
      cy.get('#bouncer-error_email').should('have.text','Por favor, preencha esse campo')
   })
    it('Formulário para conversar com consultor da empresa pelo whatsapp', () => {
      cy.visit('https://testes.autoforce.com.br/dealer-bmw-desafio/')
      cy.get(':nth-child(3) > a > .list-vehicles-land__item > .btn').type('Competition M Track')
      cy.get('.cta-box--whatsapp .button--whatsapp').click()
      cy.get('.form-modal__body input[name=name]').type('Sidney Barbosa')
      cy.get('.form-modal__body input[name=email]').type('sidneybarbosa1999@gmail.com')
      cy.get('.form-modal__body input[name=phone]').type('61 981184989')
      cy.get('.form-modal__body input[name=cpf]').type('04892694193')
      cy.get('.form-modal__body [data-type=select-one]').click()
      .contains('São Paulo').click()
      cy.get('.modal__overlay .button--whatsapp').click()
      
    
  })
  it('Mostrar mensagem de campo obrigatório no formulário de whatsapp', () => {
    cy.visit('https://testes.autoforce.com.br/dealer-bmw-desafio/')
    cy.get(':nth-child(3) > a > .list-vehicles-land__item > .btn').type('Competition M Track')
    cy.get('.cta-box--whatsapp .button--whatsapp').click()
    cy.get('.modal__overlay .button--whatsapp').click()
    cy.get('#bouncer-error_name').should('have.text','Por favor, preencha esse campo')
    cy.get('#bouncer-error_email').should('have.text','Por favor, preencha esse campo')
      cy.get('#bouncer-error_phone').should('have.text','Por favor, preencha esse campo')
      cy.get('#bouncer-error_cpf').should('have.text','Por favor, preencha esse campo')
    
})
it('Limpar campos do formulário de WhatsApp', () => {
  cy.visit('https://testes.autoforce.com.br/dealer-bmw-desafio/')
  cy.get(':nth-child(3) > a > .list-vehicles-land__item > .btn').type('Competition M Track')
  cy.get('.cta-box--whatsapp .button--whatsapp').click()
  cy.get('.form-modal__body input[name=name]').type('Sidney Barbosa')
  cy.get('.form-modal__body input[name=email]').type('sidneybarbosa1999@gmail.com')
  cy.get('.form-modal__body input[name=phone]').type('61 981184989')
  cy.get('.form-modal__body input[name=cpf]').type('04892694193')
  cy.get('.form-modal__body [data-type=select-one]').click()
  .contains('São Paulo').click()
  cy.get('.clear-fields').click()
  cy.get('.form-modal__body input[name=name]').should('have.text','')
  cy.get('.form-modal__body input[name=email]').should('have.text','')
  cy.get('.form-modal__body input[name=phone]').should('have.text','')
  cy.get('.form-modal__body input[name=cpf]').should('have.text','')
  
})
})
